#!/bin/bash

echo "🚀 Setting up yabai..."

echo ""
echo "📋 REQUIRED MANUAL STEPS:"
echo "========================="
echo ""
echo "1. Grant Accessibility permissions to yabai:"
echo "   - Open System Settings → Privacy & Security → Accessibility"
echo "   - Click the lock to make changes"
echo "   - Add yabai to the list: $(which yabai)"
echo "   - Check the box to enable it"
echo ""
echo "2. Grant Accessibility + Input Monitoring permissions to skhd:"
echo "   - Same Settings page, add: $(which skhd)"
echo ""
echo "3. For macOS Sonoma and later (if using scripting addition):"
echo "   - You may need to partially disable SIP (System Integrity Protection)"
echo "   - This is optional but provides more advanced window management features"
echo ""
echo "4. After granting permissions:"
echo "   - Run: yabai --restart-service"
echo "   - Or: brew services restart yabai"
echo ""

echo "⚙️  Current yabai location: $(which yabai)"
echo "🎯 Yabai config: ~/.yabairc -> $(readlink ~/.yabairc)"
echo ""
echo "🧪 Testing accessibility (you should see spaces info after granting permissions):"
echo "   yabai -m query --spaces"
echo ""
echo "✅ Setup complete! Follow the manual steps above to finish configuration."
