#!/usr/bin/env sh

# Refresh Übersicht to prevent simple-bar freezing on yabai restart
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

# ===== Loading Scripting Additions =====

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

# ===== Tiling setting =====

yabai -m config layout                      bsp

yabai -m config top_padding                 0
yabai -m config bottom_padding              48
yabai -m config left_padding                10
yabai -m config right_padding               10
yabai -m config window_gap                  10

# ===== Mouse =====

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config mouse_drop_action           swap

# ===== Window =====

yabai -m config window_origin_display       default
yabai -m config window_placement            second_child
yabai -m config window_shadow               on
yabai -m config window_opacity              off
yabai -m config window_opacity_duration     0.25
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9

yabai -m config window_animation_duration   0.25
yabai -m config window_animation_easing     ease_out_circ

# ===== Border =====

yabai -m config window_border               off
yabai -m config window_border_width         2
yabai -m config active_window_border_color  0xff40ff00
yabai -m config normal_window_border_color  0xff555555
yabai -m config insert_feedback_color       0xffd75f5f

# ===== Split ratios =====

yabai -m config split_ratio                 0.50
yabai -m config split_type                  auto
yabai -m config auto_balance                off

# ===== General =====

yabai -m config external_bar                main:0:0
yabai -m config menubar_opacity             100
yabai -m config window_zoom_persist         on
yabai -m config window_insertion_point      focused
yabai -m config display_arrangement_order   default

# ===== Rules =====

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Console$" manage=off
yabai -m rule --add app="^Übersicht$" manage=off

echo "yabai configuration loaded.."
